# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4e909df885d7d91a0a2a8dab4d5ed37aeb9b9122252ffaf95ea8e87a5622aba8fe8d6a6058fd957fc867ace44a5e374641b85c9ced9bf9639de2a3d5c0811bfe

test:
  secret_key_base: cc6db80ecdd0a448996b27c7cd23fdc271918837b02145e184b9810138fbb0cd46b18403c8e85ac5c8ed87ad0a7052377b8ac77fccfcc66fdc3d95cb3d3920c4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
